# Generated by Django 4.0.4 on 2022-04-26 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foremanorderupdate',
            options={'verbose_name': 'Корректировка бригадира', 'verbose_name_plural': 'Корректировки бригадиров'},
        ),
        migrations.AlterModelTable(
            name='foremanorderupdate',
            table='foreman_order_update',
        ),
    ]
