# Generated by Django 4.0.4 on 2022-04-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraservice',
            name='cleaning_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время уборки'),
        ),
    ]
